on:
  workflow_call:
    inputs:
      test_project_path:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
        default: '8.x'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-actions.yml
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Test
        run: dotnet test ${{ inputs.test_project_path }}