on:
  workflow_call:
    inputs:
      test_project_path:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
        default: '10.x'
      no_build:
        type: boolean
        default: true
      build_configuration:
        type: string
        default: 'Release'
      verbosity:
        type: string
        default: 'n'
      name:
        type: string
        default: 'Unit Tests'

jobs:
  unit-tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Test With Build
        if: ${{ !inputs.no_build }}
        run: |
          dotnet test ${{ inputs.test_project_path }} -v ${{ inputs.verbosity }} --no-build -c ${{ inputs.build_configuration }}

      - name: Test Without Build
        if: ${{ inputs.no_build }}
        run: |
          dotnet test ${{ inputs.test_project_path }} -v ${{ inputs.verbosity }} -c ${{ inputs.build_configuration }}