on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
        default: '8.x'
      package_version:
        required: true
        type: string
    secrets:
      nuget_api_key:
        required: true

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: ${{ inputs.dotnet_version }}
      build_mode: 'Debug'

  pack:
    needs: build
    uses: ./.github/workflows/dotnet-pack.yml
    with:
      dotnet_version: ${{ inputs.dotnet_version }}
      package_version: ${{ inputs.package_version }}
    secrets:
      nuget_api_key: ${{ secrets.nuget_api_key }}