on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
        default: '10.x'
      build_mode:
        type: string
        default: 'Release'
      build_path:
        type: string
        default: '.'

jobs:
  build:
    name: .NET Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build
      run: dotnet build ${{ inputs.build_path }} -c ${{ inputs.build_mode }}
