on:
  workflow_call:
    inputs:
      docker_compose_file_path:
        required: true
        type: string
      test_project_path:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
        default: '8.x'
      build_configuration:
        type: string
        default: 'Release'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Start Docker Compose
      run: docker compose -f ${{ inputs.docker_compose_file_path }} up -d && sleep 10

    - name: Test
      run: |
        dotnet test ${{ inputs.test_project_path }} -c ${{ inputs.build_configuration }}