name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:  
    inputs:
      organization:
        required: true
        type: string
      project:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
        default: '8.x'
      test_project_path:
        required: true
        type: string
      dotnet_test_verbosity:
        required: false
        type: string
        default: 'n'
      stryker_enable:
        required: false
        type: boolean
        default: true
      unit_test_project_path:
        required: true
        type: string
      domain_stryker_config_path:
        required: true
        type: string
      application_stryker_config_path:
        required: true
        type: string
      stryker_log_level:
        required: false
        type: string
        default: 'info'
      integration_test_project_path:
        required: true
        type: string
      docker_compose_file_path:
        required: true
        type: string
    secrets:
      sonar_token:
        required: true
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

      - name: test and analyze
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
        shell: powershell
        run: |
          ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"${{inputs.project}}" /o:"${{inputs.organization}}" /d:sonar.token="${{ secrets.sonar_token }}" /v:${{inputs.dotnet_version}} /d:sonar.dotnet.excludeTestProjects=true /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml"
          dotnet test ${{ inputs.test_project_path }} -v ${{inputs.dotnet_test_verbosity}} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="TestResults/"
          ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.sonar_token }}"

      - name: Install Stryker
        if: ${{ inputs.stryker_enable }}
        run: dotnet tool install -g dotnet-stryker

      - name: Run Stryker Domain
        if: ${{ inputs.stryker_enable }}
        run: dotnet stryker -tp ${{inputs.unit_test_project_path}} -f ${{inputs.domain_stryker_config_path}} -V ${{inputs.stryker_log_level}}
      
      - name: Run Stryker Application
        if: ${{ inputs.stryker_enable }}
        run: dotnet stryker -tp ${{inputs.unit_test_project_path}} -f ${{inputs.application_stryker_config_path}} -V ${{inputs.stryker_log_level}}

