on:
  workflow_call:
    inputs:
      build_path:
        type: string
        default: '.'
      dotnet_version:
        required: true
        type: string
        default: '10.x'
      stryker_enable:
        type: boolean
        default: true
      stryker_config_path:
        type: string
      stryker_log_level:
        type: string
        default: 'info'
      stryker_publish_dashboard_report:
        type: boolean
        default: false
      stryker_dashboard_project:
        type: string
        default: ${{ github.com/inputs.repository_owner/github.repository }}
      stryker_dashboard_version:
        type: string
        default: ${{ github.run_number }}
      stryker_dashboard_module:
        type: string
        default: ''
      stryker_report_name:
        type: string
        default: 'mutation-tests-contracts-result.json'
      stryker_dashboard_base_url:
        type: string
        default: 'https://dashboard.stryker-mutator.io'
      test_no_build:
        type: boolean
        default: true
      test_project_path:
        type: string
      test_verbosity:
        type: string
        default: 'n'
    secrets:
      stryker_dashboard_api_key:
        required: false
jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: ${{ inputs.dotnet_version }}
      build_mode: 'Release'
      build_path: ${{ inputs.build_path }}

  unit-tests:
    uses: ./.github/workflows/dotnet-unit-test.yml
    needs: build
    with:
      test_project_path: ${{ inputs.test_project_path }}
      dotnet_version: ${{ inputs.dotnet_version }}
      verbosity: ${{ inputs.test_verbosity }}
      no_build: ${{ inputs.test_no_build }}

  mutation-tests:
    if: ${{ inputs.stryker_enable && inputs.stryker_config_path != '' }}
    needs: build
    uses: ./.github/workflows/dotnet-mutation-test.yml
    with:
      name: 'Mutation Tests'
      test_project_path: ${{ inputs.test_project_path }}
      stryker_config_path: ${{ inputs.stryker_config_path }}
      dotnet_version: ${{ inputs.dotnet_version }}
      log_level: ${{ inputs.stryker_log_level }}
      publish_dashboard_report: ${{ inputs.stryker_publish_dashboard_report }}
      dashboard_project: ${{ inputs.stryker_dashboard_project || github.com/inputs.repository_owner/github.repository }}
      dashboard_version: ${{ inputs.stryker_dashboard_version || github.run_number }}
      dashboard_module: ${{ inputs.stryker_dashboard_module }}
      dashboard_base_url: ${{ inputs.stryker_dashboard_base_url }}
      report_name: ${{ inputs.stryker_report_name }}
    secrets:
      dashboard_api_key: ${{ secrets.stryker_dashboard_api_key }}

