on:
  workflow_call:  
    inputs:
      test_project_path:
        required: true
        type: string
      stryker_config_path: 
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
        default: '8.x'
      log_level:
        type: string
        default: 'info'
      name:
        type: string
        default: 'Mutation Tests'

jobs:
  mutation-tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Install Stryker
        run: dotnet tool install -g dotnet-stryker

      - name: Run Stryker
        run: dotnet stryker -tp ${{inputs.test_project_path}} -f ${{inputs.stryker_config_path}} -V ${{inputs.log_level}}
