on:
  workflow_call:
    inputs:
      organization:
        type: string
        default: ''
      project:
        type: string
        default: ''
      build_path:
        type: string
        default: '.'
      dotnet_version:
        required: true
        type: string
        default: '10.x'
      test_no_build:
        type: boolean
        default: true
      unit_test_project_path:
        type: string
      stryker_enable:
        type: boolean
        default: true
      stryker_log_level:
        type: string
        default: 'info'
      stryker_domain_config_path:
        type: string
      stryker_application_config_path:
        type: string
      stryker_publish_dashboard_report:
        type: boolean
        default: false
      stryker_dashboard_project:
        type: string
        default: ''
      stryker_dashboard_version:
        type: string
        default: ''
      stryker_dashboard_module_domain:
        type: string
        default: ''
      stryker_domain_report_name:
        type: string
        default: 'mutation-tests-domain-result.json'
      stryker_dashboard_module_application:
        type: string
        default: ''
      stryker_application_report_name:
        type: string
        default: 'mutation-tests-application-result.json'
      stryker_dashboard_base_url:
        type: string
        default: 'https://dashboard.stryker-mutator.io'
      integration_test_project_path:
        type: string
      docker_compose_file_path:
        type: string
      unit_test_verbosity:
        type: string
        default: 'n'
      sonar_validation:
        type: boolean
        default: true
      sonar_host_url:
        type: string
        default: 'https://sonarcloud.io'
    secrets:
      sonar_token:
      stryker_dashboard_api_key:

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: ${{ inputs.dotnet_version }}
      build_mode: 'Release'
      build_path: ${{ inputs.build_path }}

  unit-tests-with-sonar-scanner:
    if: ${{ inputs.unit_test_project_path != '' && inputs.sonar_validation }}
    uses: ./.github/workflows/dotnet-unit-test-with-sonar-scanner.yml
    needs: build
    with:
      organization: ${{ inputs.organization || github.repository_owner }}
      project: ${{ inputs.project || github.repository }}
      dotnet_version: ${{ inputs.dotnet_version }}
      unit_test_verbosity: ${{ inputs.unit_test_verbosity }}
      unit_test_project_path: ${{ inputs.unit_test_project_path }}
      sonar_host_url: ${{ inputs.sonar_host_url }}
      no_build: ${{ inputs.test_no_build }}
      build_configuration: 'Release'
    secrets:
      sonar_token: ${{ secrets.sonar_token }}

  mutation-tests-domain:
    if: ${{ inputs.unit_test_project_path != '' && inputs.stryker_enable && inputs.stryker_domain_config_path != '' }}
    needs: build
    uses: ./.github/workflows/dotnet-mutation-test.yml
    with:
      test_project_path: ${{ inputs.unit_test_project_path }}
      stryker_config_path: ${{ inputs.stryker_domain_config_path }}
      dotnet_version: ${{ inputs.dotnet_version }}
      log_level: ${{ inputs.stryker_log_level }}
      name: 'Domain Mutation Tests'
      publish_dashboard_report: ${{ inputs.stryker_publish_dashboard_report }}
      dashboard_project: ${{ inputs.stryker_dashboard_project || format('github.com/{0}', github.repository) }}
      dashboard_version: ${{ inputs.stryker_dashboard_version || github.run_number }}
      dashboard_module: ${{ inputs.stryker_dashboard_module_domain }}
      dashboard_base_url: ${{ inputs.stryker_dashboard_base_url }}
      report_name: ${{ inputs.stryker_domain_report_name }}
    secrets:
      dashboard_api_key: ${{ secrets.stryker_dashboard_api_key }}

  mutation-tests-application:
    if: ${{ inputs.unit_test_project_path != '' && inputs.stryker_enable && inputs.stryker_application_config_path != '' }}
    needs: build
    uses: ./.github/workflows/dotnet-mutation-test.yml
    with:
      test_project_path: ${{ inputs.unit_test_project_path }}
      stryker_config_path: ${{ inputs.stryker_application_config_path }}
      dotnet_version: ${{ inputs.dotnet_version }}
      log_level: ${{ inputs.stryker_log_level }}
      name: 'Application Mutation Tests'
      publish_dashboard_report: ${{ inputs.stryker_publish_dashboard_report }}
      dashboard_project: ${{ inputs.stryker_dashboard_project || format('github.com/{0}', github.repository) }}
      dashboard_version: ${{ inputs.stryker_dashboard_version || github.run_number }}
      dashboard_module: ${{ inputs.stryker_dashboard_module_application }}
      dashboard_base_url: ${{ inputs.stryker_dashboard_base_url }}
      report_name: ${{ inputs.stryker_application_report_name }}
    secrets:
      dashboard_api_key: ${{ secrets.stryker_dashboard_api_key }}

  integration-test:
    if: ${{ inputs.integration_test_project_path != '' }}
    uses: ./.github/workflows/dotnet-integration-test.yml
    needs: build
    with:
      docker_compose_file_path: ${{ inputs.docker_compose_file_path }}
      test_project_path: ${{ inputs.integration_test_project_path }}
      dotnet_version: ${{ inputs.dotnet_version }}
      build_configuration: 'Release'

